### ISSUE TITLE
menu is broken

### ISSUE THREAD

**Issue by faenil** [nemomobile/fingerterm#10]
How to reproduce:
1) start fingerterm
2) open menu
3) try to scroll

you'll see the keys underneath get the touch events instead of the menu :)

Maybe @thp can have a look?

**Comment by thp** [comment]
Tempted to close this as wontfix, or is this still reproducible with recent images (if there exist any) on N9/N950?

**Comment by faenil** [comment]
I'll let you know as soon as I install the latest image on the n950 ;)

**Comment by faenil** [comment]
working! let's close this
