### ISSUE TITLE
Version information lacking

### ISSUE THREAD

**Issue by FireyFly** [nemomobile/fingerterm#30]
The [updateversion.sh](https://github.com/nemomobile/fingerterm/blob/master/updateversion.sh) script updates the file `version.h` with the latest version from [qtc_packaging/debian_harmattan/changelog](https://github.com/nemomobile/fingerterm/blob/master/qtc_packaging/debian_harmattan/changelog). I guess it's a good idea to keep the "upstream" versions apart from the [releases](https://github.com/nemomobile/fingerterm/releases) in this repository, but the release version numbers should probably be available in *some* form. Currently I can't really tell what version of Fingerterm is in the Sailfish repositories, since the about dialog simply contains 'FingerTerm 1.0.3'; presumably the actual version isn't a year old.

**Comment by thp** [comment]
This has been fixed in the silica branch: https://github.com/nemomobile/fingerterm/commit/68e48dfd8c5cdd5d5e7e74e7ad135994cbcd4088 -- keeping it open until the master branch has the fix also (or is replaced by the silica branch).

**Comment by thp** [comment]
Proposed fix: https://github.com/nemomobile/fingerterm/pull/42
