### ISSUE TITLE
Chinese character display is not perfect

### ISSUE THREAD

**Issue by 0312birdzhang** [nemomobile/fingerterm#51]
![screenshot-11-07-15-00-20-23](https://cloud.githubusercontent.com/assets/1762041/8631874/1e6be62a-27b6-11e5-8de9-0f26dd6fc8b3.png)

I use FontLoader to change Text font,and want to recompile it,but fails with this log
```shell
[mersdk@SailfishSDK fingerterm]$ mb2 -t SailfishOS-armv7hl qmake 

Building target platforms: armv7hl-meego-linux
Building for target armv7hl-meego-linux
Executing(%build): /bin/sh -e /var/tmp/rpm-tmp.lzMG0G
sh: /home/mersdk/share/fingerterm/updateversion.sh: /bin/bash^M: bad interpreter: No such file or directory
g++ -c -pipe -O2 -Wall -W -D_REENTRANT -fPIE -DQT_NO_DEBUG -DQT_QUICK_LIB -DQT_GUI_LIB -DQT_QML_LIB -DQT_NETWORK_LIB -DQT_DBUS_LIB -DQT_FEEDBACK_LIB -DQT_CORE_LIB -I/usr/share/qt5/mkspecs/linux-g++ -I. -I. -I/usr/include/nemonotifications-qt5 -I/usr/include/qt5 -I/usr/include/qt5/QtQuick -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtQml -I/usr/include/qt5/QtNetwork -I/usr/include/qt5/QtDBus -I/usr/include/qt5/QtFeedback -I/usr/include/qt5/QtCore -I. -o main.o main.cpp
g++ -c -pipe -O2 -Wall -W -D_REENTRANT -fPIE -DQT_NO_DEBUG -DQT_QUICK_LIB -DQT_GUI_LIB -DQT_QML_LIB -DQT_NETWORK_LIB -DQT_DBUS_LIB -DQT_FEEDBACK_LIB -DQT_CORE_LIB -I/usr/share/qt5/mkspecs/linux-g++ -I. -I. -I/usr/include/nemonotifications-qt5 -I/usr/include/qt5 -I/usr/include/qt5/QtQuick -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtQml -I/usr/include/qt5/QtNetwork -I/usr/include/qt5/QtDBus -I/usr/include/qt5/QtFeedback -I/usr/include/qt5/QtCore -I. -o util.o util.cpp
g++ -c -pipe -O2 -Wall -W -D_REENTRANT -fPIE -DQT_NO_DEBUG -DQT_QUICK_LIB -DQT_GUI_LIB -DQT_QML_LIB -DQT_NETWORK_LIB -DQT_DBUS_LIB -DQT_FEEDBACK_LIB -DQT_CORE_LIB -I/usr/share/qt5/mkspecs/linux-g++ -I. -I. -I/usr/include/nemonotifications-qt5 -I/usr/include/qt5 -I/usr/include/qt5/QtQuick -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtQml -I/usr/include/qt5/QtNetwork -I/usr/include/qt5/QtDBus -I/usr/include/qt5/QtFeedback -I/usr/include/qt5/QtCore -I. -o qrc_resources.o qrc_resources.cpp
virtual memory exhausted: Cannot allocate memory
make: *** [qrc_resources.o] Error 1
error: Bad exit status from /var/tmp/rpm-tmp.lzMG0G (%build)


RPM build errors:
    Bad exit status from /var/tmp/rpm-tmp.lzMG0G (%build)
[mersdk@SailfishSDK fingerterm]$ free -m
             total       used       free     shared    buffers     cached
Mem:           497        203        293          0          7        151
-/+ buffers/cache:         44        452
Swap:            0          0          0
[mersdk@SailfishSDK fingerterm]$ df -h
Filesystem            Size  Used Avail Use% Mounted on
rootfs                4.0G  2.4G  1.6G  60% /
/dev/root             4.0G  2.4G  1.6G  60% /
devtmpfs              249M     0  249M   0% /dev
tmpfs                 249M     0  249M   0% /dev/shm
tmpfs                 249M  1.0M  248M   1% /run
tmpfs                 249M     0  249M   0% /sys/fs/cgroup
tmpfs                 249M     0  249M   0% /tmp
none                  164G   45G  119G  28% /etc/ssh/authorized_keys
none                  164G   45G  119G  28% /home/mersdk/share
none                  164G   45G  119G  28% /host_targets
none                  164G   45G  119G  28% /etc/mersdk/share
none                  164G   45G  119G  28% /home/src1
[mersdk@SailfishSDK fingerterm]$ 

```

And i use SailfishSDK on ubuntu,disabled shadow build ,also fails with the same log

So,what's the right way to compile this project?

Or can you fix the display style of Chinese character?

**Comment by 0312birdzhang** [comment]
Lastes:

I had fix it,but the package size is very large :smile: 

The errors is because if put the font file to qrc,this cause the <code>virtual memory exhausted: Cannot allocate memory</code>

![screenshot-11-07-15-10-41-54](https://cloud.githubusercontent.com/assets/1762041/8631994/f7af2886-27b9-11e5-9f76-67b9ccf0b40c.png)

**Comment by 0312birdzhang** [comment]
:joy:  Only right via SailfishSDK ,WTF?

**Comment by 0312birdzhang** [comment]
Use other way to solved it

```shell
vi /usr/share/applications/fingerterm.desktop
```
Replace <code>Exec=fingerterm</code>to <code>Exec=bash -c "export LANG=C;fingerterm"</code>

**Comment by 0312birdzhang** [comment]
I think i should reopen this issue. 
Because we should not modify the desktop file everytime this software update or sailfish system upgrade.
It's not really resolve the issue.

What about modify fingerterm.desktop.nemo to
```
[Desktop Entry]
Type=Application
Name=Terminal
Exec=bash -c "export LANG=en_US.UTF-8;fingerterm"
Icon=icon-l-terminal
```
Other languages may have effets,please verify it.

**Comment by pvuorela** [comment]
I don't fully understand what's the issue here. Would it be Fingerterm displaying some Chinese characters bad, in device or with SDK, or problems modifying the code? Chinese characters appear to work for me on Jolla phone.

**Comment by 0312birdzhang** [comment]
@pvuorela  Look at the image https://github.com/nemomobile/fingerterm/issues/51#issue-94427015
,compare it with https://github.com/nemomobile/fingerterm/issues/51#issuecomment-120565153 .

**Comment by pvuorela** [comment]
I see them using different fonts, but no indication why they are different, what is the environment, and no trace of chinese characters.

**Comment by 0312birdzhang** [comment]
@pvuorela  Sorry for my poor English,my meaning is zh_CN.UTF-8 environment lead to the issue.

You can change your system language to Simple Chinese,reboot jolla,and open Terminal.

The issue will appear.

**Comment by pvuorela** [comment]
Now got it, zh_CN.utf8 locale seems to actually change the font of Fingerterm. Interesting.

**Comment by 0312birdzhang** [comment]
@pvuorela :sweat_smile: It's very interesting.

**Comment by pvuorela** [comment]
Problem here was that main monospace font doesn't claim to support Chinese. As a result, a non-monospace Chinese font was selected as primary one. Problem isn't Fingerterm per se, so I'm already closing this. Sailfish will get adjusted font selection rules on later update.
