### ISSUE TITLE
Caps lock doesn't work with TOHKBD

### ISSUE THREAD

**Issue by Nicd** [nemomobile/fingerterm#54]
Turning on caps lock in TOHKBD doesn't affect FingerTerm. Normal shift works fine but caps lock just does nothing. Using latest 1.1.9 with TOHKBD package 0.5.4. No idea if this affects other external keyboards.

**Comment by sam-hobbs** [comment]
I also have this issue, same versions.

**Comment by kimmoli** [comment]
Looks like keyPress handler converts keys toLower or toUpper depending on Shift modifier state.

https://github.com/nemomobile/fingerterm/blob/master/terminal.cpp#L184

Shift is "not pressed" when capslock is active. (Or actually it is with TOHKBD2 on Sailfish 1.1.6.x, as there the Capslock was broken, and it was made in TOHKBD2 daemon by pressing Shift key)

Related findings from Internet: 
* https://bugreports.qt.io/browse/QTBUG-48293
* http://www.qtforum.org/article/32572/how-to-determine-if-capslock-is-on-crossplatform.html (Not applicable for Sailfish?)

**Comment by urjaman** [comment]
I didnt read what you did put i got inspired by your comment when it was shorter and did this:
https://github.com/urjaman/thumbterm/commit/0229a3330c572bf98d661c06d44ee67e379e2bf2
